// === MIA — Legal & Compliance (Faz 2) ===
// Gerçek rıza akışları + kabul audit trail + sürüm takibi.
// Statik metin değil: kabul edildiğinde consents tablosuna yazılır ve sürümlenir.
// Global `supabase`, `currentLang` js/app.js'ten gelir (varsa). Bağımsız da çalışır.
//
// Açık API (window.MIALegal):
//   VERSIONS                         → doküman sürümleri
//   DISCLAIMERS(lang)                → AI/sorumluluk/rapor metinleri
//   recordConsent(keys, opts)        → kabul kaydı (DB + localStorage)
//   hasConsent(key)                  → Promise<bool> (geçerli sürüm kabul edildi mi)
//   ensureImageProcessingConsent()   → Promise<bool> (gerekirse modal gösterir)

(function () {
    var L = (window.MIALegal = window.MIALegal || {});

    // Doküman sürümleri — metin değişince burayı yükselt → yeniden rıza tetiklenir.
    L.VERSIONS = {
        terms: "1.0",
        privacy: "1.0",
        kvkk: "1.0",
        image_processing: "1.0",
        cross_border: "1.0",
    };

    function lang() { return (typeof currentLang !== "undefined" ? currentLang : (localStorage.getItem("mia_lang") || "tr")); }
    function isTR() { return lang() === "tr"; }

    // Yeniden kullanılabilir yasal metinler (rapor/sonuç/e-posta).
    L.DISCLAIMERS = function (lng) {
        var tr = (lng || lang()) === "tr";
        return {
            ai: tr
                ? "Bu analiz yapay zeka destekli bir ön değerlendirmedir; sertifikalı bir İSG uzmanının yerine geçmez."
                : "This analysis is an AI-assisted preliminary assessment and does not replace a certified OHS professional.",
            liability: tr
                ? "MIA, tespit sonuçlarının eksiksizliğini veya hatasızlığını garanti etmez. Nihai İSG kararları yetkili kişilerce verilmelidir."
                : "MIA does not guarantee the completeness or accuracy of detections. Final OHS decisions must be made by authorized personnel.",
            report: tr
                ? "Bu rapor MIA yapay zeka analizi ile otomatik oluşturulmuştur ve yasal İSG denetiminin yerine geçmez."
                : "This report is auto-generated by MIA AI analysis and does not substitute a legal OHS inspection.",
            crossBorder: tr
                ? "Yüklenen görüntüler tespit amacıyla yurt dışındaki işleyicilerde (Roboflow / Modal — ABD) işlenebilir."
                : "Uploaded images may be processed by sub-processors abroad (Roboflow / Modal — USA) for detection purposes.",
        };
    };

    function sb() { return window.supabase && window.supabase.from ? window.supabase : null; }
    function localKey(key) { return "mia.consent." + key + "." + (L.VERSIONS[key] || "1.0"); }

    // Kabul kaydı: her anahtar için consents'e satır + localStorage işareti.
    L.recordConsent = function (keys, opts) {
        opts = opts || {};
        keys = Array.isArray(keys) ? keys : [keys];
        var client = sb();
        var page = location.pathname;
        var ua = navigator.userAgent || "";
        return (client ? client.auth.getSession() : Promise.resolve({ data: {} })).then(function (r) {
            var session = r && r.data && r.data.session;
            var uid = session ? session.user.id : null;
            var email = (session && session.user.email) || opts.email || null;
            var subject = uid ? ("user:" + uid) : (email ? ("email:" + email) : "anon");
            var rows = keys.map(function (k) {
                try { localStorage.setItem(localKey(k), "1"); } catch (e) {}
                return {
                    user_id: uid, email: email, subject: subject,
                    document_key: k, version: L.VERSIONS[k] || "1.0",
                    user_agent: ua, page: page,
                };
            });
            if (!client) return true; // DB yoksa en azından localStorage işaretlendi
            return client.from("consents").insert(rows).then(function (res) {
                if (res.error) console.warn("[MIA] consent kaydı hata:", res.error.message);
                return !res.error;
            });
        }).catch(function (e) { console.warn("[MIA] recordConsent hata:", e); return false; });
    };

    // Geçerli sürüm kabul edilmiş mi? (localStorage hızlı yol; giriş varsa DB teyit)
    L.hasConsent = function (key) {
        try { if (localStorage.getItem(localKey(key)) === "1") return Promise.resolve(true); } catch (e) {}
        var client = sb();
        if (!client) return Promise.resolve(false);
        return client.auth.getSession().then(function (r) {
            var session = r && r.data && r.data.session;
            if (!session) return false;
            return client.from("consents").select("id")
                .eq("user_id", session.user.id).eq("document_key", key)
                .eq("version", L.VERSIONS[key] || "1.0").limit(1)
                .then(function (res) {
                    var ok = !res.error && res.data && res.data.length > 0;
                    if (ok) { try { localStorage.setItem(localKey(key), "1"); } catch (e) {} }
                    return ok;
                });
        }).catch(function () { return false; });
    };

    // Görüntü işleme + sınır ötesi aktarım rızası — gerekirse modal göster.
    L.ensureImageProcessingConsent = function () {
        return L.hasConsent("image_processing").then(function (ok) {
            if (ok) return true;
            return showConsentModal();
        });
    };

    function showConsentModal() {
        return new Promise(function (resolve) {
            var tr = isTR();
            var d = L.DISCLAIMERS();
            var ov = document.createElement("div");
            ov.setAttribute("style", "position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:9999;display:flex;align-items:center;justify-content:center;padding:1rem;");
            var card = document.createElement("div");
            card.setAttribute("style", "max-width:520px;width:100%;background:#141414;color:#fff;border:1px solid rgba(212,175,55,.3);border-radius:14px;padding:1.5rem;font-family:Inter,-apple-system,Arial,sans-serif;");
            card.innerHTML =
                '<div style="font-size:22px;font-weight:800;color:#D4AF37;margin-bottom:.5rem;">MIA</div>' +
                '<h2 style="font-size:18px;margin:.2rem 0 1rem;">' + (tr ? "Görüntü İşleme Onayı" : "Image Processing Consent") + "</h2>" +
                '<p style="font-size:14px;line-height:1.6;color:#cfcfcf;margin:0 0 .8rem;">' +
                (tr
                    ? "Yüklediğiniz video, koruyucu ekipman (KKD) tespiti amacıyla yapay zeka ile işlenecektir. Görüntüler çalışanlara ait kişisel veri içerebilir ve KVKK kapsamında işlenir."
                    : "Your uploaded video will be processed by AI to detect personal protective equipment (PPE). Images may contain workers' personal data, processed under Turkish data-protection law (KVKK).") +
                "</p>" +
                '<p style="font-size:13px;line-height:1.6;color:#b0b0b0;margin:0 0 .8rem;">' + d.crossBorder + "</p>" +
                '<p style="font-size:12px;line-height:1.5;color:#8a8a8a;margin:0 0 1.2rem;">' + d.ai + "</p>" +
                '<label style="display:flex;gap:.5rem;align-items:flex-start;font-size:13px;color:#ddd;margin-bottom:1rem;cursor:pointer;">' +
                '<input type="checkbox" id="miaConsentChk" style="margin-top:3px;width:16px;height:16px;accent-color:#D4AF37;">' +
                "<span>" + (tr
                    ? "Görüntülerin yukarıdaki amaç ve koşullarla işlenmesini ve sınır ötesi aktarımını <b>açık rıza</b> ile kabul ediyorum."
                    : "I give my <b>explicit consent</b> to process and transfer the images under the conditions above.") + "</span></label>" +
                '<div style="display:flex;gap:.6rem;justify-content:flex-end;">' +
                '<button id="miaConsentCancel" style="padding:.6rem 1rem;border-radius:8px;border:1px solid #444;background:transparent;color:#ddd;cursor:pointer;">' + (tr ? "Vazgeç" : "Cancel") + "</button>" +
                '<button id="miaConsentOk" style="padding:.6rem 1.1rem;border-radius:8px;border:none;background:#D4AF37;color:#0A0A0A;font-weight:700;cursor:pointer;opacity:.5;" disabled>' + (tr ? "Onayla ve Devam Et" : "Accept & Continue") + "</button>" +
                '<a href="kvkk.html" target="_blank" style="align-self:center;font-size:12px;color:#9a8a5a;">KVKK</a>' +
                "</div>";
            ov.appendChild(card);
            document.body.appendChild(ov);
            var chk = card.querySelector("#miaConsentChk");
            var ok = card.querySelector("#miaConsentOk");
            chk.addEventListener("change", function () { ok.disabled = !chk.checked; ok.style.opacity = chk.checked ? "1" : ".5"; });
            function close(v) { try { document.body.removeChild(ov); } catch (e) {} resolve(v); }
            card.querySelector("#miaConsentCancel").addEventListener("click", function () { close(false); });
            ok.addEventListener("click", function () {
                ok.disabled = true;
                L.recordConsent(["image_processing", "cross_border"]).then(function () { close(true); });
            });
        });
    }
})();
